name: Run PHP Script and Commit Changes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-php-script:
    permissions:
      issues: write
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Run PHP Script
      run: php autopilot.php
      env:
        GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

